class CountryHints {
  static const Map<String, String> hints = {
    'AF': 'xx xxx xxxx',
    'AL': 'xxx xxx xxx',
    'DZ': 'x xx xx xx xx',
    'AS': 'xxx xxx xxxx',
    'AD': 'xxx xxx',
    'AO': 'xxx xxx xxx',
    'AI': 'xxx xxx xxxx',
    'AG': 'xxx xxx xxxx',
    'AR': 'xx xxxx xxxx',
    'AM': 'xx xxx xxx',
    'AW': 'xxx xxxx',
    'AU': 'xxx xxx xxx',
    'AT': 'xxxx xxxxxxx',
    'AZ': 'xx xxx xx xx',
    'BS': 'xxx xxx xxxx',
    'BH': 'xxxx xxxx',
    'BD': 'xxxx xxxxxx',
    'BB': 'xxx xxx xxxx',
    'BY': 'xx xxx xx xx',
    'BE': 'xxx xx xx xx',
    'BZ': 'xxx xxxx',
    'BJ': 'xx xx xx xx',
    'BM': 'xxx xxx xxxx',
    'BT': 'xx xx xx xx',
    'BO': 'x xxxx xxxx',
    'BA': 'xx xxx xxx',
    'BW': 'xx xxx xxx',
    'BR': 'xx xxxxx xxxx',
    'IO': 'xxx xxx xxxx',
    'VG': 'xxx xxx xxxx',
    'BN': 'xxx xxxx',
    'BG': 'xxx xxx xxx',
    'BF': 'xx xx xx xx',
    'BI': 'xx xx xx xx',
    'KH': 'xx xxx xxx',
    'CM': 'x xx xx xx xx',
    'CA': 'xxx xxx xxxx',
    'CV': 'xxx xxxx',
    'BQ': 'x xxx xxxx',
    'KY': 'xxx xxx xxxx',
    'CF': 'xx xx xx xx',
    'TD': 'xx xx xx xx',
    'CL': 'x xxxx xxxx',
    'CN': 'xxx xxxx xxxx',
    'CX': 'x xxxx xxxx',
    'CC': 'xxxx xxx xxx',
    'CO': 'xxx xxx xxxx',
    'KM': 'xx xx xx xx',
    'CG': 'xx xxx xxxx',
    'CD': 'xxx xxx xxx',
    'CK': 'xx xxx',
    'CR': 'xxxx xxxx',
    'CI': 'xx xx xx xx xx',
    'HR': 'xx xxx xxxx',
    'CU': 'x xxx xxxx',
    'CW': 'x xxx xxxx',
    'CY': 'xx xxxxxx',
    'CZ': 'xxx xxx xxx',
    'DK': 'xx xx xx xx',
    'DJ': 'xx xx xx xx',
    'DM': 'xxx xxx xxxx',
    'DO': 'xxx xxx xxxx',
    'EC': 'x xxxx xxxx',
    'EG': 'xx xxxx xxxx',
    'SV': 'xxxx xxxx',
    'GQ': 'xxx xxx xxx',
    'ER': 'x xxx xxx',
    'EE': 'xxxx xxxx',
    'ET': 'xx xxx xxxx',
    'FO': 'xx xxxx',
    'FJ': 'xx xxxx',
    'FI': 'xxx xxx xxxx',
    'FR': 'x xx xx xx xx',
    'GF': 'xxx xx xx xx',
    'PF': 'xx xx xx xx',
    'GA': 'x xx xx xx',
    'GM': 'xxx xxxx',
    'GE': 'xxx xx xx xx',
    'DE': 'xxx xxxxxxxx',
    'GH': 'xx xxx xxxx',
    'GI': 'xxx xxxxx',
    'GR': 'xx xxxx xxxx',
    'GL': 'xx xx xx',
    'GD': 'xxx xxx xxxx',
    'GP': 'xxx xx xx xx',
    'GU': 'xxx xxx xxxx',
    'GT': 'xxxx xxxx',
    'GG': 'xxxx xxxxxx',
    'GN': 'xxx xx xx xx',
    'GW': 'x xxx xxxx',
    'GY': 'xxx xxxx',
    'HT': 'xxxx xxxx',
    'HN': 'xxxx xxxx',
    'HK': 'xxxx xxxx',
    'HU': 'xx xxx xxxx',
    'IS': 'xxx xxxx',
    'IN': 'xxxxx xxxxx',
    'ID': 'xxx xxxx xxxx',
    'IR': 'xxx xxx xxxx',
    'IQ': 'xxx xxx xxxx',
    'IE': 'xx xxx xxxx',
    'IM': 'xxxx xxxxxx',
    'IL': 'xx xxx xxxx',
    'IT': 'xx xxxx xxxx',
    'JM': 'xxx xxx xxxx',
    'JP': 'xx xxxx xxxx',
    'JE': 'xxxx xxxxxx',
    'JO': 'x xxxx xxxx',
    'KZ': 'xxx xxx xxxx',
    'KE': 'xxx xxx xxx',
    'KI': 'xx xxx',
    'XK': 'xx xxx xxx',
    'KW': 'xxxx xxxx',
    'KG': 'xxx xxx xxx',
    'LA': 'xx xx xxx xxx',
    'LV': 'xx xxx xxx',
    'LB': 'xx xxx xxx',
    'LS': 'xxxx xxxx',
    'LR': 'xx xxx xxxx',
    'LY': 'xx xxx xxxx',
    'LI': 'xxx xxxx',
    'LT': 'xxx xx xxx',
    'LU': 'xxx xxx xxx',
    'MO': 'xxxx xxxx',
    'MK': 'xx xxx xxx',
    'MG': 'xx xx xxx xx',
    'MW': 'x xxxx xxxx',
    'MY': 'xx xxx xxxx',
    'MV': 'xxx xxxx',
    'ML': 'xx xx xx xx',
    'MT': 'xxxx xxxx',
    'MH': 'xxx xxxx',
    'MQ': 'xxx xx xx xx',
    'MR': 'xx xx xx xx',
    'MU': 'xxxx xxxx',
    'YT': 'xxx xx xx xx',
    'MX': 'xx xx xxxx xxxx',
    'FM': 'xxx xxxx',
    'MD': 'xxxx xxxx',
    'MC': 'xx xx xx xx',
    'MN': 'xxxx xxxx',
    'ME': 'xx xxx xxx',
    'MS': 'xxx xxx xxxx',
    'MA': 'x xx xx xx xx',
    'MZ': 'xx xx xxxxx',
    'MM': 'x xxx xxx xxx',
    'NA': 'xx xxx xxxx',
    'NR': 'xxx xxxx',
    'NP': 'xx xxxx xxxx',
    'NL': 'xx xxxxxxxx',
    'NC': 'xx xx xx',
    'NZ': 'xx xxx xxxx',
    'NI': 'xxxx xxxx',
    'NE': 'xx xx xx xx',
    'NG': 'xxx xxx xxxx',
    'NU': 'xxxx',
    'NF': 'xx xxx',
    'KP': 'xxx xxx xxxx',
    'MP': 'xxx xxx xxxx',
    'NO': 'xxx xx xxx',
    'OM': 'xxxx xxxx',
    'PK': 'xxx xxxxxxx',
    'PW': 'xxx xxxx',
    'PS': 'xx xxx xxxx',
    'PA': 'xxxx xxxx',
    'PG': 'xxxx xxxx',
    'PY': 'xxx xxx xxx',
    'PE': 'xxx xxx xxx',
    'PH': 'xxx xxx xxxx',
    'PL': 'xxx xxx xxx',
    'PT': 'xxx xxx xxx',
    'PR': 'xxx xxx xxxx',
    'QA': 'xxxx xxxx',
    'RE': 'x xx xx xx xx',
    'RO': 'xxx xxx xxx',
    'RU': 'xxx xxx xx xx',
    'RW': 'xxx xxx xxx',
    'BL': 'x xx xx xx xx',
    'SH': 'xxxx',
    'KN': 'xxx xxx xxxx',
    'LC': 'xxx xxx xxxx',
    'MF': 'x xx xx xx xx',
    'PM': 'xx xx xx',
    'VC': 'xxx xxx xxxx',
    'WS': 'xx xxxx',
    'SM': 'xx xxxxxx',
    'ST': 'xxx xxxx',
    'SA': 'xx xxx xxxx',
    'SN': 'xx xxx xx xx',
    'RS': 'xx xxx xxxx',
    'SC': 'x xxx xxx',
    'SL': 'xx xxx xxx',
    'SG': 'xxxx xxxx',
    'SX': 'xxx xxxx',
    'SK': 'xxx xxx xxx',
    'SI': 'xx xxx xxx',
    'SB': 'xx xxxxx',
    'SO': 'x xxx xxxx',
    'ZA': 'xx xxx xxxx',
    'KR': 'xx xxxx xxxx',
    'SS': 'xx xxx xxxx',
    'ES': 'xxx xxx xxx',
    'LK': 'xx xxx xxxx',
    'SD': 'xx xxx xxxx',
    'SR': 'xxx xxxx',
    'SJ': 'xxx xx xxx',
    'SZ': 'xxxx xxxx',
    'SE': 'xx xxx xx xx',
    'CH': 'xx xxx xx xx',
    'SY': 'xx xxx xxxx',
    'TW': 'xxx xxx xxx',
    'TJ': 'xx xxx xxxx',
    'TZ': 'xxx xxx xxx',
    'TH': 'xx xxx xxxx',
    'TL': 'xxxx xxxx',
    'TG': 'xx xx xx xx',
    'TK': 'xxxx',
    'TO': 'xxx xxxx',
    'TT': 'xxx xxx xxxx',
    'TN': 'xx xxx xxx',
    'TR': 'xxx xxx xx xx',
    'TM': 'xx xxxxxx',
    'TC': 'xxx xxx xxxx',
    'TV': 'xxxxx',
    'UG': 'xxx xxxxxx',
    'UA': 'xx xxx xxxx',
    'AE': 'x xxx xxxx',
    'GB': 'xxxx xxxxxx',
    'US': 'xxx xxx xxxx',
    'UY': 'x xxx xxx xxx',
    'UZ': 'xx xxx xx xx',
    'VU': 'xxx xxxx',
    'VA': 'xxx xxx xxxx',
    'VE': 'xxx xxx xxxx',
    'VN': 'xx xxx xx xx',
    'WF': 'xx xx xx',
    'YE': 'x xxx xxx',
    'ZM': 'xx xxx xxxx',
    'ZW': 'x xxx xxxx',
  };
}
